import FWCore.ParameterSet.Config as cms

from RecoVertex.AdaptiveVertexFinder.candidateVertexArbitratorDefault_cfi import candidateVertexArbitratorDefault

candidateVertexArbitrator = candidateVertexArbitratorDefault.clone()

from RecoVertex.AdaptiveVertexFinder.candidateVertexArbitratorScoutingDefault_cfi import candidateVertexArbitratorScoutingDefault

candidateVertexArbitratorScouting = candidateVertexArbitratorScoutingDefault.clone()


